actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -68,9 +68,25 @@ jobs:
           exit 127
           fi
         done
-        sleep 30
       env:
         REPO: azurecontinerregistery
+    
+    - name: Whitelisted Check
+      run: |
+        count=0
+        while [ $count -lt 100 ]; do
+            az acr check-health --name "$REPO"
+            if [ $? -eq 0 ]; then
+                echo "ACR is Accessible"
+                exit 127
+            else
+                echo "The ACR health check failed. Retrying after 5 seconds."
+                sleep 5
+            fi
+            count=$((count+1))
+        done
+      env:
+        REPO: azurecontinerregistery                
         
     - name: Azure Container Registry Login
       uses: Azure/docker-login@v1.0.1
