actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -71,22 +71,22 @@ jobs:
       env:
         REPO: azurecontinerregistery
     
-    - name: Whitelisted Check
-      run: |
-        count=0
-        while [ $count -lt 100 ]; do
-            az acr check-health --name "$REPO"
-            if [ $? -eq 0 ]; then
-                echo "ACR is Accessible"
-                exit 127
-            else
-                echo "The ACR health check failed. Retrying after 5 seconds."
-                sleep 5
-            fi
-            count=$((count+1))
-        done
-      env:
-        REPO: azurecontinerregistery                
+    - name: Whitelist checker
+      uses: Azure/cli@v2.0.0
+      with:
+        inlineScript: |
+            count=0
+            while [ $count -lt 100 ]; do
+                az acr check-health --name "azurecontinerregistery"
+                if [ $? -eq 0 ]; then
+                    echo "ACR is Accessible"
+                    exit 127
+                else
+                    echo "The ACR health check failed. Retrying after 5 seconds."
+                    sleep 5
+                fi
+                count=$((count+1))
+            done              
         
     - name: Azure Container Registry Login
       uses: Azure/docker-login@v1.0.1
